#OAuth tokens and key for Audience API.
audience_api:
  
  #Key and Secret for App with API permissions.
  consumer_key:
  consumer_secret:
  
  #Access Token/Secret
  access_token:
  access_token_secret:
  
  app_id:  #Not used in code, but useful troubleshooting information.
  


